fix: Provider verification fails when no pacts are found
pact-foundation/pact-provider-verifier pull request #67
Opened 2021-03-21 18:17 UTC by jjacobskind

I recently implemented Pact in one of my JS services. While doing so, I was surprised to find that my jest tests were passing, even though there were no pacts in my broker that matched the `consumerVersionSelectors` specified in the test.

On one hand, I can see why this behavior might be desired, as it is true that the provider verification did not fail against any pacts that were specified.

On the other hand, my expectation when verifying a provider is that there is a matching pact to verify against. If the provider passes when no pact is present, I might mistakenly think that it passed against a valid pact. As a newcomer to Pact, it seems like this scenario should fail

2021-03-22 05:07 UTC, bethesque commented
Thanks for this contribution. We need to maintain the existing behaviour for all the current users, so let's add an option to the command to tell it what to do when there are no pacts. @uglyog I seem to remember there's an option to toggle this in the JVM. What is it called? @mefellows did you have an existing option added on top to any of the wrapper languages that does this?

2021-03-22 05:09 UTC, bethesque commented
Feature request here: https://pact.canny.io/feature-requests/p/add-failifnopactsfound-flag-for-verification

2021-03-22 05:14 UTC, uglyog commented
Pact-JVM has an `@IgnoreNoPactsToVerify` annotation that can be added to the test class

2021-03-24 00:27 UTC, mefellows commented
There is an option in Pact Go called `FailIfNoPactsFound` that defaults to `true`. It looks at the length of verified interactions (looking at the JSON output of the Ruby verifier) and if it is of zero length and the option is `false`, it emits a warning but doesn't fail the test.

2021-03-24 21:33 UTC, bethesque commented
Let's add a `--fail-if-no-pacts-found` option that defaults to false to maintain the current behaviour then @jjacobskind.

2021-03-27 23:20 UTC, jjacobskind commented
@bethesque Thanks for the feedback. Just pushed that change

2021-03-28 15:32 UTC, jjacobskind commented on spec/lib/pact/provider_verifier/app_spec.rb
> +          context "at least one pact fails verification" do
Realized that my initial implementation broke this functionality. Seems pretty important, so added this spec

2021-03-28 23:15 UTC, bethesque requested changes
Looks great, just a couple of typos.

2021-03-28 23:15 UTC, bethesque commented on README.md
> +      [--fail_if_no_pacts_found]
Thor translates the underscores into dashes, so the option is actually `--fail-if-no-pacts-found`

2021-03-28 23:15 UTC, bethesque commented on spec/lib/pact/provider_verifier/app_spec.rb
> +              expect(Cli::RunPactVerification).to receive(:call).twice
Ah, the old pacrs! They must be verified!

2021-03-29 01:12 UTC, jjacobskind commented
@bethesque Good catches. Just pushed up those fixes

2021-03-29 03:20 UTC, merged